<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YouA0Lm' shared service.

return $this->privates['.service_locator.YouA0Lm'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['formAuthenticator' => function (): \App\Security\LoginAuthenticator {
    return ($this->privates['App\Security\LoginAuthenticator'] ?? $this->load('getLoginAuthenticatorService.php'));
}, 'guardHandler' => function () {
    return ($this->privates['security.authentication.guard_handler'] ?? $this->load('getSecurity_Authentication_GuardHandlerService.php'));
}, 'passwordEncoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'));
}]);
