<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\TypeExtension\TextareaSizeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/src/Form/TypeExtension/TextareaSizeExtension.php';

return $this->privates['App\Form\TypeExtension\TextareaSizeExtension'] = new \App\Form\TypeExtension\TextareaSizeExtension();
