<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4RdD7U\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4RdD7U/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG4RdD7U.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG4RdD7U\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerG4RdD7U\srcDevDebugProjectContainer([
    'container.build_hash' => 'G4RdD7U',
    'container.build_id' => 'd96e6520',
    'container.build_time' => 1623712127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4RdD7U');
