<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Z1bTP2\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Z1bTP2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2Z1bTP2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2Z1bTP2\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2Z1bTP2\srcDevDebugProjectContainer([
    'container.build_hash' => '2Z1bTP2',
    'container.build_id' => '6bc67d41',
    'container.build_time' => 1623356394,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Z1bTP2');
