<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrhJNRR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrhJNRR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKrhJNRR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKrhJNRR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKrhJNRR\srcDevDebugProjectContainer([
    'container.build_hash' => 'KrhJNRR',
    'container.build_id' => '5d30ecd6',
    'container.build_time' => 1623418554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrhJNRR');
